name: CI avec SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Installation des dependances
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Scan SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
        -Dsonar.projectKey=Kharnaim_EXOSIPython \
        -Dsonar.organization=your_organization_key \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
